services:
  finance-tracker:
    build:
      context: .
    container_name: finance-tracker
    restart: unless-stopped
    ports:
      - "8999:8080"
    environment:
      #   - MIGRATIONS=/migrations
      - DB=sqlite:////app/data/db.sqlite
    volumes:
      - .:/app/app
      - /home/anderson/homelab/finance-tracker/data:/app/data
      # - ./migrations:/migrations
